"""Add WALLET_TRANSFER to TransactionType

Revision ID: 48729b0a7467
Revises: d9171f28b3cf
Create Date: 2026-07-06 15:40:00.145681

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '48729b0a7467'
down_revision: Union[str, None] = 'd9171f28b3cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions') as batch_op:
        batch_op.alter_column('tx_type',
               existing_type=sa.VARCHAR(length=11),
               type_=sa.Enum('DATA', 'WALLET_FUND', 'WALLET_TRANSFER', 'AIRTIME', 'CABLE', 'ELECTRICITY', 'EXAM', name='transactiontype'),
               existing_nullable=False)
    op.add_column('users', sa.Column('profile_image_url', sa.String(length=512), nullable=True))
    op.add_column('users', sa.Column('webhook_url', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('webhook_secret', sa.String(length=128), nullable=True))
    with op.batch_alter_table('virtual_accounts') as batch_op:
        batch_op.alter_column('provider',
               existing_type=sa.VARCHAR(length=8),
               type_=sa.Enum('MONNIFY', 'PAYSTACK', 'BILLSTACK', name='virtualaccountprovider'),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('virtual_accounts', 'provider',
               existing_type=sa.Enum('MONNIFY', 'PAYSTACK', 'BILLSTACK', name='virtualaccountprovider'),
               type_=sa.VARCHAR(length=8),
               existing_nullable=False)
    op.drop_column('users', 'webhook_secret')
    op.drop_column('users', 'webhook_url')
    op.drop_column('users', 'profile_image_url')
    with op.batch_alter_table('transactions') as batch_op:
        batch_op.alter_column('tx_type',
                   existing_type=sa.Enum('DATA', 'WALLET_FUND', 'WALLET_TRANSFER', 'AIRTIME', 'CABLE', 'ELECTRICITY', 'EXAM', name='transactiontype'),
                   type_=sa.VARCHAR(length=11),
                   existing_nullable=False)
    # ### end Alembic commands ###
