"""Add Agent Tracking Models

Revision ID: 4e81b4f14959
Revises: 29ab4217df7f
Create Date: 2026-05-24 16:45:59.531543

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e81b4f14959'
down_revision: Union[str, None] = '29ab4217df7f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reward_campaigns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('campaign_type', sa.Enum('REFERRAL', 'VOLUME', name='campaigntype'), nullable=False),
    sa.Column('target_metric', sa.String(length=64), nullable=False),
    sa.Column('target_value', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('reward_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reward_campaigns_id'), 'reward_campaigns', ['id'], unique=False)
    op.create_table('agent_rewards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'CREDITED', 'FAILED', name='agentrewardstatus'), nullable=False),
    sa.Column('transaction_reference', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['campaign_id'], ['reward_campaigns.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_rewards_agent_id'), 'agent_rewards', ['agent_id'], unique=False)
    op.create_index(op.f('ix_agent_rewards_id'), 'agent_rewards', ['id'], unique=False)
    op.create_index(op.f('ix_agent_rewards_transaction_reference'), 'agent_rewards', ['transaction_reference'], unique=False)
    op.create_table('agent_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=False),
    sa.Column('total_data_mb', sa.Integer(), nullable=False),
    sa.Column('total_airtime_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_transactions', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_stats_agent_id'), 'agent_stats', ['agent_id'], unique=True)
    op.create_index(op.f('ix_agent_stats_id'), 'agent_stats', ['id'], unique=False)
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_wallets_id'), table_name='wallets')
    op.drop_index(op.f('ix_wallet_ledger_id'), table_name='wallet_ledger')
    # Skipped drop_constraint for users.referred_by_id to avoid SQLite errors
    op.drop_index(op.f('ix_users_id'), table_name='users')
    # Skipped alter_column for users.referral_code to avoid SQLite errors
    op.drop_index(op.f('ix_transactions_id'), table_name='transactions')
    op.create_index('ix_transactions_recipient_phone', 'transactions', ['recipient_phone'], unique=False)
    op.drop_index(op.f('ix_referrals_reward_transaction_reference'), table_name='referrals')
    op.drop_index(op.f('ix_referrals_referrer_id'), table_name='referrals')
    op.drop_index(op.f('ix_referrals_referred_user_id'), table_name='referrals')
    op.drop_index(op.f('ix_referrals_referral_code_used'), table_name='referrals')
    op.drop_index(op.f('ix_referrals_qualifying_transaction_reference'), table_name='referrals')
    op.drop_index(op.f('ix_referrals_id'), table_name='referrals')
    op.create_index('ix_referrals_reward_reference', 'referrals', ['reward_transaction_reference'], unique=False)
    op.create_index('ix_referrals_referred_user', 'referrals', ['referred_user_id'], unique=1)
    op.drop_index(op.f('ix_referral_contributions_transaction_reference'), table_name='referral_contributions')
    op.drop_index(op.f('ix_referral_contributions_referral_id'), table_name='referral_contributions')
    op.drop_index(op.f('ix_referral_contributions_id'), table_name='referral_contributions')
    op.drop_index(op.f('ix_pricing_rules_id'), table_name='pricing_rules')
    op.drop_index(op.f('ix_data_plans_network'), table_name='data_plans')
    op.drop_index(op.f('ix_data_plans_id'), table_name='data_plans')
    # Skipped alter_column for data_plans to avoid SQLite errors
    op.drop_index(op.f('ix_api_logs_id'), table_name='api_logs')
    op.drop_index(op.f('ix_agent_stats_id'), table_name='agent_stats')
    op.drop_index(op.f('ix_agent_stats_agent_id'), table_name='agent_stats')
    op.drop_table('agent_stats')
    op.drop_index(op.f('ix_agent_rewards_transaction_reference'), table_name='agent_rewards')
    op.drop_index(op.f('ix_agent_rewards_id'), table_name='agent_rewards')
    op.drop_index(op.f('ix_agent_rewards_agent_id'), table_name='agent_rewards')
    op.drop_table('agent_rewards')
    op.drop_index(op.f('ix_reward_campaigns_id'), table_name='reward_campaigns')
    op.drop_table('reward_campaigns')
    # ### end Alembic commands ###
