"""Add api_price to data_plans

Revision ID: 701b5994e2ff
Revises: fe526561aa01
Create Date: 2026-09-20 13:42:14.270538

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '701b5994e2ff'
down_revision: Union[str, None] = 'fe526561aa01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('data_plans', sa.Column('api_price', sa.Numeric(precision=12, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('data_plans', 'api_price')
    # ### end Alembic commands ###
