"""Add target fields to promo_codes

Revision ID: 75d718ff057d
Revises: ca80b66e7b09
Create Date: 2026-09-30 16:31:31.329850

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '75d718ff057d'
down_revision: Union[str, None] = 'ca80b66e7b09'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('financial_ledger', 'status',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('financial_ledger', 'description',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('financial_ledger', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(now())'))
    op.alter_column('financial_ledger', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.create_index(op.f('ix_financial_ledger_id'), 'financial_ledger', ['id'], unique=False)
    op.create_foreign_key(None, 'financial_ledger', 'users', ['created_by_id'], ['id'])
    op.add_column('promo_codes', sa.Column('applicable_network', sa.String(length=20), nullable=False))
    op.add_column('promo_codes', sa.Column('applicable_plan_size', sa.String(length=20), nullable=False))
    op.add_column('promo_codes', sa.Column('target_audience', sa.String(length=20), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('promo_codes', 'target_audience')
    op.drop_column('promo_codes', 'applicable_plan_size')
    op.drop_column('promo_codes', 'applicable_network')
    op.drop_constraint(None, 'financial_ledger', type_='foreignkey')
    op.drop_index(op.f('ix_financial_ledger_id'), table_name='financial_ledger')
    op.alter_column('financial_ledger', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('financial_ledger', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(now())'))
    op.alter_column('financial_ledger', 'description',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('financial_ledger', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
