"""Add target fields to promo_codes

Revision ID: 75d718ff057d
Revises: ca80b66e7b09
Create Date: 2026-09-30 16:31:31.329850

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '75d718ff057d'
down_revision: Union[str, None] = 'ca80b66e7b09'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('promo_codes', sa.Column('applicable_network', sa.String(length=20), nullable=False, server_default='ALL'))
    op.add_column('promo_codes', sa.Column('applicable_plan_size', sa.String(length=20), nullable=False, server_default='ALL'))
    op.add_column('promo_codes', sa.Column('target_audience', sa.String(length=20), nullable=False, server_default='ALL'))
    op.add_column('promo_codes', sa.Column('is_fixed_price', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('promo_codes', 'is_fixed_price')
    op.drop_column('promo_codes', 'target_audience')
    op.drop_column('promo_codes', 'applicable_plan_size')
    op.drop_column('promo_codes', 'applicable_network')
    # ### end Alembic commands ###
