"""Add fallback provider columns to DataPlan

Revision ID: 7aed13a5f796
Revises: 48729b0a7467
Create Date: 2026-07-18 01:21:57.237313

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7aed13a5f796'
down_revision: Union[str, None] = '48729b0a7467'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('data_plans', sa.Column('fallback_provider', sa.String(length=64), nullable=True))
    op.add_column('data_plans', sa.Column('fallback_provider_plan_id', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_data_plans_fallback_provider'), 'data_plans', ['fallback_provider'], unique=False)
    op.create_index(op.f('ix_data_plans_fallback_provider_plan_id'), 'data_plans', ['fallback_provider_plan_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_data_plans_fallback_provider_plan_id'), table_name='data_plans')
    op.drop_index(op.f('ix_data_plans_fallback_provider'), table_name='data_plans')
    op.drop_column('data_plans', 'fallback_provider_plan_id')
    op.drop_column('data_plans', 'fallback_provider')
    # ### end Alembic commands ###
