"""add_announcement_button_columns

Revision ID: cad7025451dd
Revises: aa3685e1a68f
Create Date: 2026-06-24 21:18:31.528291

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cad7025451dd'
down_revision: Union[str, None] = 'aa3685e1a68f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    if not inspector.has_table('broadcast_announcements'):
        # Create table with all columns including button_label and button_link
        op.create_table(
            'broadcast_announcements',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('title', sa.String(length=120), nullable=False),
            sa.Column('message', sa.Text(), nullable=False),
            sa.Column('level', sa.Enum('INFO', 'SUCCESS', 'WARNING', 'CRITICAL', name='announcementlevel'), nullable=False),
            sa.Column('is_active', sa.Boolean(), nullable=False, server_default='true'),
            sa.Column('starts_at', sa.DateTime(timezone=True), nullable=True),
            sa.Column('ends_at', sa.DateTime(timezone=True), nullable=True),
            sa.Column('created_by_email', sa.String(length=255), nullable=True),
            sa.Column('button_label', sa.String(length=50), nullable=True),
            sa.Column('button_link', sa.String(length=255), nullable=True),
            sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
            sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
            sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_broadcast_announcements_id'), 'broadcast_announcements', ['id'], unique=False)
        op.create_index('ix_broadcast_announcements_active_window', 'broadcast_announcements', ['is_active', 'starts_at', 'ends_at'], unique=False)
    else:
        columns = [c['name'] for c in inspector.get_columns('broadcast_announcements')]
        if 'button_label' not in columns:
            op.add_column('broadcast_announcements', sa.Column('button_label', sa.String(length=50), nullable=True))
        if 'button_link' not in columns:
            op.add_column('broadcast_announcements', sa.Column('button_link', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('broadcast_announcements', 'button_link')
    op.drop_column('broadcast_announcements', 'button_label')
    # ### end Alembic commands ###
