"""Add VirtualAccount model

Revision ID: d28149582b84
Revises: 7ffa1244f905
Create Date: 2026-05-17 09:16:45.780955

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd28149582b84'
down_revision: Union[str, None] = '7ffa1244f905'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('virtual_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.Enum('MONNIFY', 'PAYSTACK', name='virtualaccountprovider'), nullable=False),
    sa.Column('account_number', sa.String(length=32), nullable=False),
    sa.Column('account_name', sa.String(length=255), nullable=False),
    sa.Column('bank_name', sa.String(length=255), nullable=False),
    sa.Column('bank_code', sa.String(length=16), nullable=False),
    sa.Column('customer_reference', sa.String(length=64), nullable=False),
    sa.Column('reservation_reference', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', name='virtualaccountstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reservation_reference')
    )
    op.create_index(op.f('ix_virtual_accounts_customer_reference'), 'virtual_accounts', ['customer_reference'], unique=True)
    op.create_index(op.f('ix_virtual_accounts_id'), 'virtual_accounts', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_virtual_accounts_id'), table_name='virtual_accounts')
    op.drop_index(op.f('ix_virtual_accounts_customer_reference'), table_name='virtual_accounts')
    op.drop_table('virtual_accounts')
    # ### end Alembic commands ###
