"""Add popup fields to BroadcastAnnouncement

Revision ID: fe526561aa01
Revises: e6476650fd37
Create Date: 2026-09-12 13:06:47.668353

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe526561aa01'
down_revision: Union[str, None] = 'e6476650fd37'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('broadcast_announcements', sa.Column('image_url', sa.String(length=500), nullable=True))
    op.add_column('broadcast_announcements', sa.Column('is_popup', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('broadcast_announcements', 'is_popup')
    op.drop_column('broadcast_announcements', 'image_url')
    # ### end Alembic commands ###
